// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
<<<<<<< HEAD
using StyleMateAPI.Data;
=======
using StyleMate1._1.Data;
>>>>>>> 856aa784dc6d940e6820f47978450581557e3a84

#nullable disable

namespace StyleMate.API.Migrations
{
    [DbContext(typeof(StyleMateContext))]
    partial class StyleMateContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StyleMate1._1.Models.Conjunto", b =>
                {
                    b.Property<int>("IdConjunto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdConjunto"));

                    b.Property<string>("Estacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estilo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorIdUtilizador")
                        .HasColumnType("int");

                    b.HasKey("IdConjunto");

                    b.HasIndex("UtilizadorIdUtilizador");

                    b.ToTable("Conjuntos");
                });

            modelBuilder.Entity("StyleMate1._1.Models.ConjuntoRoupa", b =>
                {
                    b.Property<int>("IdConjunto")
                        .HasColumnType("int");

                    b.Property<int>("IdRoupa")
                        .HasColumnType("int");

                    b.HasKey("IdConjunto", "IdRoupa");

                    b.HasIndex("IdRoupa");

                    b.ToTable("ConjuntoRoupas");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Evento", b =>
                {
                    b.Property<int>("IdEvento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEvento"));

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorIdUtilizador")
                        .HasColumnType("int");

                    b.HasKey("IdEvento");

                    b.HasIndex("UtilizadorIdUtilizador");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Mala", b =>
                {
                    b.Property<int>("IdMala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMala"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorIdUtilizador")
                        .HasColumnType("int");

                    b.HasKey("IdMala");

                    b.HasIndex("UtilizadorIdUtilizador");

                    b.ToTable("Malas");
                });

            modelBuilder.Entity("StyleMate1._1.Models.MalaConjunto", b =>
                {
                    b.Property<int>("IdMala")
                        .HasColumnType("int");

                    b.Property<int>("IdConjunto")
                        .HasColumnType("int");

                    b.HasKey("IdMala", "IdConjunto");

                    b.HasIndex("IdConjunto");

                    b.ToTable("MalaConjuntos");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Roupa", b =>
                {
                    b.Property<int>("IdRoupa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRoupa"));

                    b.Property<double?>("CategoriaConfidence")
                        .HasColumnType("float");

                    b.Property<string>("CategoriaIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoriaUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataAdicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstacaoSugeridaIA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstacaoUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUtilizador")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRoupa");

                    b.HasIndex("IdUtilizador");

                    b.ToTable("Roupas");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Utilizador", b =>
                {
                    b.Property<int>("IdUtilizador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUtilizador"));

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoPerfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Preferencias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("IdUtilizador");

                    b.ToTable("Utilizadores");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Conjunto", b =>
                {
                    b.HasOne("StyleMate1._1.Models.Utilizador", "Utilizador")
                        .WithMany("Conjuntos")
                        .HasForeignKey("UtilizadorIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("StyleMate1._1.Models.ConjuntoRoupa", b =>
                {
                    b.HasOne("StyleMate1._1.Models.Conjunto", "Conjunto")
                        .WithMany("ConjuntosRoupas")
                        .HasForeignKey("IdConjunto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StyleMate1._1.Models.Roupa", "Roupa")
                        .WithMany()
                        .HasForeignKey("IdRoupa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjunto");

                    b.Navigation("Roupa");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Evento", b =>
                {
                    b.HasOne("StyleMate1._1.Models.Utilizador", "Utilizador")
                        .WithMany("Eventos")
                        .HasForeignKey("UtilizadorIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Mala", b =>
                {
                    b.HasOne("StyleMate1._1.Models.Utilizador", "Utilizador")
                        .WithMany("Malas")
                        .HasForeignKey("UtilizadorIdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("StyleMate1._1.Models.MalaConjunto", b =>
                {
                    b.HasOne("StyleMate1._1.Models.Conjunto", "Conjunto")
                        .WithMany()
                        .HasForeignKey("IdConjunto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StyleMate1._1.Models.Mala", "Mala")
                        .WithMany("MalaConjuntos")
                        .HasForeignKey("IdMala")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conjunto");

                    b.Navigation("Mala");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Roupa", b =>
                {
                    b.HasOne("StyleMate1._1.Models.Utilizador", "Utilizador")
                        .WithMany("Roupas")
                        .HasForeignKey("IdUtilizador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Conjunto", b =>
                {
                    b.Navigation("ConjuntosRoupas");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Mala", b =>
                {
                    b.Navigation("MalaConjuntos");
                });

            modelBuilder.Entity("StyleMate1._1.Models.Utilizador", b =>
                {
                    b.Navigation("Conjuntos");

                    b.Navigation("Eventos");

                    b.Navigation("Malas");

                    b.Navigation("Roupas");
                });
#pragma warning restore 612, 618
        }
    }
}
